import { EventEmitter } from 'events';
import { v4 as uuidv4 } from 'uuid';
import path from 'path';
import fs from 'fs';
import { db } from '../database';
import { configManager } from './ConfigManager';

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

export interface SlideContent {
    title: string;
    content?: string;
    bullets?: string[];
    imageUrl?: string;
    notes?: string;
    layout?: 'title' | 'content' | 'two-column' | 'image' | 'blank';
}

export interface PresentationRequest {
    title: string;
    slides: SlideContent[];
    theme?: 'default' | 'dark' | 'corporate' | 'creative';
    author?: string;
}

export interface ExcelSheetData {
    name: string;
    headers?: string[];
    rows: any[][];
    columnWidths?: number[];
}

export interface ExcelRequest {
    title: string;
    sheets: ExcelSheetData[];
}

export interface WordRequest {
    title: string;
    content: string | DocumentSection[];
    author?: string;
}

export interface DocumentSection {
    heading?: string;
    level?: number; // 1-6 for heading levels
    content?: string;
    bullets?: string[];
    table?: { headers: string[]; rows: string[][] };
}

export interface HTMLReportRequest {
    title: string;
    sections: DocumentSection[];
    style?: 'minimal' | 'professional' | 'modern';
    includeTableOfContents?: boolean;
}

export interface GeneratedFile {
    id: string;
    filename: string;
    file_type: string;
    file_path: string;
    full_path: string;
    mime_type: string;
    file_size: number;
}

// ============================================================================
// DOCUMENT GENERATOR SERVICE
// ============================================================================

export class DocumentGenerator extends EventEmitter {
    private outputDir: string = '';
    private pptxgenjs: any = null;
    private exceljs: any = null;
    private docx: any = null;

    constructor() {
        super();
        this.initOutputDir();
        this.loadLibraries();
    }

    private initOutputDir(): void {
        const workspaceDir = configManager.getWorkspaceDir();
        this.outputDir = path.join(workspaceDir, 'output', 'deliverables');

        if (!fs.existsSync(this.outputDir)) {
            fs.mkdirSync(this.outputDir, { recursive: true });
        }
    }

    private async loadLibraries(): Promise<void> {
        // Lazy load document generation libraries
        try {
            this.pptxgenjs = await import('pptxgenjs').then(m => m.default || m);
            console.log('[DocumentGenerator] pptxgenjs loaded');
        } catch (e) {
            console.warn('[DocumentGenerator] pptxgenjs not installed. Run: npm install pptxgenjs');
        }

        try {
            this.exceljs = await import('exceljs');
            console.log('[DocumentGenerator] exceljs loaded');
        } catch (e) {
            console.warn('[DocumentGenerator] exceljs not installed. Run: npm install exceljs');
        }

        try {
            this.docx = await import('docx');
            console.log('[DocumentGenerator] docx loaded');
        } catch (e) {
            console.warn('[DocumentGenerator] docx not installed. Run: npm install docx');
        }
    }

    // ========================================================================
    // POWERPOINT GENERATION
    // ========================================================================

    async generatePresentation(request: PresentationRequest, userId: string = 'default'): Promise<GeneratedFile> {
        if (!this.pptxgenjs) {
            throw new Error('pptxgenjs not installed. Run: npm install pptxgenjs');
        }

        const pptx = new this.pptxgenjs();

        // Set presentation properties
        pptx.title = request.title;
        pptx.author = request.author || 'AI Co-Worker';
        pptx.company = 'Generated by AI Partner';

        // Apply theme colors
        const theme = this.getPresentationTheme(request.theme || 'default');

        // Generate slides
        for (const slideData of request.slides) {
            const slide = pptx.addSlide();

            // Set background
            slide.bkgd = theme.background;

            if (slideData.layout === 'title' || !slideData.layout) {
                // Title slide
                slide.addText(slideData.title, {
                    x: 0.5, y: 2.5, w: 9, h: 1.5,
                    fontSize: 36, bold: true, color: theme.titleColor,
                    align: 'center'
                });

                if (slideData.content) {
                    slide.addText(slideData.content, {
                        x: 0.5, y: 4, w: 9, h: 1,
                        fontSize: 18, color: theme.textColor,
                        align: 'center'
                    });
                }
            } else {
                // Content slide with title
                slide.addText(slideData.title, {
                    x: 0.5, y: 0.3, w: 9, h: 0.8,
                    fontSize: 28, bold: true, color: theme.titleColor
                });

                // Add bullets or content
                if (slideData.bullets && slideData.bullets.length > 0) {
                    const bulletText = slideData.bullets.map(b => ({
                        text: b,
                        options: { bullet: true, color: theme.textColor }
                    }));

                    slide.addText(bulletText, {
                        x: 0.5, y: 1.3, w: 9, h: 4,
                        fontSize: 18, color: theme.textColor,
                        valign: 'top'
                    });
                } else if (slideData.content) {
                    slide.addText(slideData.content, {
                        x: 0.5, y: 1.3, w: 9, h: 4,
                        fontSize: 16, color: theme.textColor,
                        valign: 'top'
                    });
                }
            }

            // Add notes if present
            if (slideData.notes) {
                slide.addNotes(slideData.notes);
            }
        }

        // Generate unique filename
        const id = uuidv4();
        const filename = `${this.sanitizeFilename(request.title)}_${Date.now()}.pptx`;
        const relativePath = path.join(id, filename);
        const fullPath = path.join(this.outputDir, relativePath);

        // Ensure directory exists
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });

        // Save file
        await pptx.writeFile({ fileName: fullPath });

        // Get file size
        const stats = fs.statSync(fullPath);

        // Register in database
        await this.registerFile({
            id,
            filename,
            file_type: 'pptx',
            file_path: relativePath,
            title: request.title,
            user_id: userId,
            file_size: stats.size
        });

        console.log(`[DocumentGenerator] Generated presentation: ${filename}`);

        return {
            id,
            filename,
            file_type: 'pptx',
            file_path: relativePath,
            full_path: fullPath,
            mime_type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            file_size: stats.size
        };
    }

    private getPresentationTheme(theme: string): any {
        const themes: Record<string, any> = {
            default: {
                background: 'FFFFFF',
                titleColor: '333333',
                textColor: '666666'
            },
            dark: {
                background: '1a1a2e',
                titleColor: 'eaeaea',
                textColor: 'b0b0b0'
            },
            corporate: {
                background: 'f5f5f5',
                titleColor: '003366',
                textColor: '444444'
            },
            creative: {
                background: 'fff5e6',
                titleColor: 'e65c00',
                textColor: '4d4d4d'
            }
        };

        return themes[theme] || themes.default;
    }

    // ========================================================================
    // EXCEL GENERATION
    // ========================================================================

    async generateExcel(request: ExcelRequest, userId: string = 'default'): Promise<GeneratedFile> {
        if (!this.exceljs) {
            throw new Error('exceljs not installed. Run: npm install exceljs');
        }

        const workbook = new this.exceljs.Workbook();
        workbook.creator = 'AI Co-Worker';
        workbook.created = new Date();

        for (const sheetData of request.sheets) {
            const sheet = workbook.addWorksheet(sheetData.name);

            // Add headers if present
            if (sheetData.headers && sheetData.headers.length > 0) {
                const headerRow = sheet.addRow(sheetData.headers);
                headerRow.font = { bold: true };
                headerRow.fill = {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: 'FFE0E0E0' }
                };
            }

            // Add data rows
            for (const row of sheetData.rows) {
                sheet.addRow(row);
            }

            // Set column widths
            if (sheetData.columnWidths) {
                sheetData.columnWidths.forEach((width, index) => {
                    sheet.getColumn(index + 1).width = width;
                });
            } else {
                // Auto-width based on content
                sheet.columns.forEach((column: any) => {
                    column.width = 15;
                });
            }
        }

        // Generate unique filename
        const id = uuidv4();
        const filename = `${this.sanitizeFilename(request.title)}_${Date.now()}.xlsx`;
        const relativePath = path.join(id, filename);
        const fullPath = path.join(this.outputDir, relativePath);

        // Ensure directory exists
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });

        // Save file
        await workbook.xlsx.writeFile(fullPath);

        // Get file size
        const stats = fs.statSync(fullPath);

        // Register in database
        await this.registerFile({
            id,
            filename,
            file_type: 'xlsx',
            file_path: relativePath,
            title: request.title,
            user_id: userId,
            file_size: stats.size
        });

        console.log(`[DocumentGenerator] Generated Excel: ${filename}`);

        return {
            id,
            filename,
            file_type: 'xlsx',
            file_path: relativePath,
            full_path: fullPath,
            mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            file_size: stats.size
        };
    }

    // ========================================================================
    // WORD DOCUMENT GENERATION
    // ========================================================================

    async generateWord(request: WordRequest, userId: string = 'default'): Promise<GeneratedFile> {
        if (!this.docx) {
            throw new Error('docx not installed. Run: npm install docx');
        }

        const { Document, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell } = this.docx;

        const children: any[] = [];

        // Title
        children.push(
            new Paragraph({
                text: request.title,
                heading: HeadingLevel.TITLE
            })
        );

        // Content
        if (typeof request.content === 'string') {
            // Simple string content
            const paragraphs = request.content.split('\n\n');
            for (const para of paragraphs) {
                children.push(
                    new Paragraph({
                        children: [new TextRun(para)]
                    })
                );
            }
        } else {
            // Structured sections
            for (const section of request.content) {
                if (section.heading) {
                    const headingLevel = this.getHeadingLevel(section.level || 1);
                    children.push(
                        new Paragraph({
                            text: section.heading,
                            heading: headingLevel
                        })
                    );
                }

                if (section.content) {
                    children.push(
                        new Paragraph({
                            children: [new TextRun(section.content)]
                        })
                    );
                }

                if (section.bullets) {
                    for (const bullet of section.bullets) {
                        children.push(
                            new Paragraph({
                                text: bullet,
                                bullet: { level: 0 }
                            })
                        );
                    }
                }

                if (section.table) {
                    const tableRows = [];

                    // Header row
                    tableRows.push(
                        new TableRow({
                            children: section.table.headers.map(h =>
                                new TableCell({
                                    children: [new Paragraph({ children: [new TextRun({ text: h, bold: true })] })]
                                })
                            )
                        })
                    );

                    // Data rows
                    for (const row of section.table.rows) {
                        tableRows.push(
                            new TableRow({
                                children: row.map(cell =>
                                    new TableCell({
                                        children: [new Paragraph(cell)]
                                    })
                                )
                            })
                        );
                    }

                    children.push(
                        new Table({
                            rows: tableRows
                        })
                    );
                }
            }
        }

        const doc = new Document({
            creator: request.author || 'AI Co-Worker',
            title: request.title,
            sections: [{
                children
            }]
        });

        // Generate unique filename
        const id = uuidv4();
        const filename = `${this.sanitizeFilename(request.title)}_${Date.now()}.docx`;
        const relativePath = path.join(id, filename);
        const fullPath = path.join(this.outputDir, relativePath);

        // Ensure directory exists
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });

        // Save file
        const buffer = await this.docx.Packer.toBuffer(doc);
        fs.writeFileSync(fullPath, buffer);

        // Get file size
        const stats = fs.statSync(fullPath);

        // Register in database
        await this.registerFile({
            id,
            filename,
            file_type: 'docx',
            file_path: relativePath,
            title: request.title,
            user_id: userId,
            file_size: stats.size
        });

        console.log(`[DocumentGenerator] Generated Word doc: ${filename}`);

        return {
            id,
            filename,
            file_type: 'docx',
            file_path: relativePath,
            full_path: fullPath,
            mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            file_size: stats.size
        };
    }

    private getHeadingLevel(level: number): any {
        const { HeadingLevel } = this.docx;
        const levels: Record<number, any> = {
            1: HeadingLevel.HEADING_1,
            2: HeadingLevel.HEADING_2,
            3: HeadingLevel.HEADING_3,
            4: HeadingLevel.HEADING_4,
            5: HeadingLevel.HEADING_5,
            6: HeadingLevel.HEADING_6
        };
        return levels[level] || HeadingLevel.HEADING_1;
    }

    // ========================================================================
    // HTML REPORT GENERATION
    // ========================================================================

    async generateHTML(request: HTMLReportRequest, userId: string = 'default'): Promise<GeneratedFile> {
        const style = this.getHTMLStyle(request.style || 'professional');

        let tocHtml = '';
        if (request.includeTableOfContents) {
            tocHtml = '<nav class="toc"><h2>Table of Contents</h2><ul>';
            request.sections.forEach((section, i) => {
                if (section.heading) {
                    tocHtml += `<li><a href="#section-${i}">${section.heading}</a></li>`;
                }
            });
            tocHtml += '</ul></nav>';
        }

        let contentHtml = '';
        request.sections.forEach((section, i) => {
            if (section.heading) {
                const tag = `h${section.level || 2}`;
                contentHtml += `<${tag} id="section-${i}">${section.heading}</${tag}>`;
            }

            if (section.content) {
                contentHtml += `<p>${section.content}</p>`;
            }

            if (section.bullets) {
                contentHtml += '<ul>';
                for (const bullet of section.bullets) {
                    contentHtml += `<li>${bullet}</li>`;
                }
                contentHtml += '</ul>';
            }

            if (section.table) {
                contentHtml += '<table><thead><tr>';
                for (const header of section.table.headers) {
                    contentHtml += `<th>${header}</th>`;
                }
                contentHtml += '</tr></thead><tbody>';
                for (const row of section.table.rows) {
                    contentHtml += '<tr>';
                    for (const cell of row) {
                        contentHtml += `<td>${cell}</td>`;
                    }
                    contentHtml += '</tr>';
                }
                contentHtml += '</tbody></table>';
            }
        });

        const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${request.title}</title>
    <style>${style}</style>
</head>
<body>
    <header>
        <h1>${request.title}</h1>
        <p class="meta">Generated by AI Co-Worker on ${new Date().toLocaleDateString()}</p>
    </header>
    ${tocHtml}
    <main>
        ${contentHtml}
    </main>
    <footer>
        <p>Generated by AI Partner</p>
    </footer>
</body>
</html>`;

        // Generate unique filename
        const id = uuidv4();
        const filename = `${this.sanitizeFilename(request.title)}_${Date.now()}.html`;
        const relativePath = path.join(id, filename);
        const fullPath = path.join(this.outputDir, relativePath);

        // Ensure directory exists
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });

        // Save file
        fs.writeFileSync(fullPath, html, 'utf-8');

        // Get file size
        const stats = fs.statSync(fullPath);

        // Register in database
        await this.registerFile({
            id,
            filename,
            file_type: 'html',
            file_path: relativePath,
            title: request.title,
            user_id: userId,
            file_size: stats.size
        });

        console.log(`[DocumentGenerator] Generated HTML report: ${filename}`);

        return {
            id,
            filename,
            file_type: 'html',
            file_path: relativePath,
            full_path: fullPath,
            mime_type: 'text/html',
            file_size: stats.size
        };
    }

    private getHTMLStyle(style: string): string {
        const styles: Record<string, string> = {
            minimal: `
                body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
                h1, h2, h3 { margin-top: 1.5em; }
                table { border-collapse: collapse; width: 100%; margin: 1em 0; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background: #f5f5f5; }
            `,
            professional: `
                body { font-family: 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; line-height: 1.7; color: #333; background: #fafafa; }
                header { border-bottom: 2px solid #0066cc; padding-bottom: 20px; margin-bottom: 30px; }
                h1 { color: #0066cc; }
                h2 { color: #004499; border-bottom: 1px solid #eee; padding-bottom: 10px; }
                .toc { background: #f0f5ff; padding: 20px; border-radius: 8px; margin-bottom: 30px; }
                .toc h2 { margin-top: 0; }
                table { border-collapse: collapse; width: 100%; margin: 1em 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background: #0066cc; color: white; }
                tr:nth-child(even) { background: #f9f9f9; }
                footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; text-align: center; }
            `,
            modern: `
                body { font-family: 'Inter', system-ui, sans-serif; max-width: 1000px; margin: 0 auto; padding: 40px; line-height: 1.8; color: #1a1a1a; }
                header { text-align: center; margin-bottom: 50px; }
                h1 { font-size: 2.5em; font-weight: 700; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
                h2 { font-size: 1.5em; font-weight: 600; margin-top: 2em; }
                .toc { background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); padding: 25px; border-radius: 12px; margin-bottom: 40px; }
                table { border-collapse: collapse; width: 100%; margin: 1.5em 0; border-radius: 8px; overflow: hidden; }
                th, td { padding: 14px 16px; text-align: left; }
                th { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }
                tr:nth-child(even) { background: #f8f9fc; }
                footer { margin-top: 60px; text-align: center; color: #888; font-size: 0.9em; }
            `
        };

        return styles[style] || styles.professional;
    }

    // ========================================================================
    // HELPER METHODS
    // ========================================================================

    private sanitizeFilename(name: string): string {
        return name
            .replace(/[^a-z0-9]/gi, '_')
            .replace(/_+/g, '_')
            .substring(0, 50);
    }

    private async registerFile(data: {
        id: string;
        filename: string;
        file_type: string;
        file_path: string;
        title: string;
        user_id: string;
        file_size: number;
        execution_id?: string;
        conversation_id?: string;
    }): Promise<void> {
        const mimeTypes: Record<string, string> = {
            'pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'pdf': 'application/pdf',
            'html': 'text/html'
        };

        await db.run(
            `INSERT INTO generated_files
             (id, filename, file_type, file_path, file_size, mime_type, title, user_id, execution_id, conversation_id)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
            [
                data.id,
                data.filename,
                data.file_type,
                data.file_path,
                data.file_size,
                mimeTypes[data.file_type] || 'application/octet-stream',
                data.title,
                data.user_id,
                data.execution_id || null,
                data.conversation_id || null
            ]
        );
    }

    // ========================================================================
    // PDF GENERATION (using Playwright)
    // ========================================================================

    async generatePDF(request: HTMLReportRequest, userId: string = 'default'): Promise<GeneratedFile> {
        // First generate the HTML
        const htmlContent = this.buildHTMLContent(request);

        // Generate unique filename
        const id = uuidv4();
        const filename = `${this.sanitizeFilename(request.title)}_${Date.now()}.pdf`;
        const relativePath = path.join(id, filename);
        const fullPath = path.join(this.outputDir, relativePath);

        // Ensure directory exists
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });

        let browser: any = null;
        try {
            // Try to use Playwright for PDF generation
            const playwright = await import('playwright').catch(() => null);

            if (!playwright) {
                throw new Error('Playwright not installed. Run: npm install playwright && npx playwright install chromium');
            }

            console.log('[DocumentGenerator] Generating PDF with Playwright...');

            // Launch browser
            browser = await playwright.chromium.launch({ headless: true });
            const context = await browser.newContext();
            const page = await context.newPage();

            // Set content with timeout — 'networkidle' hangs indefinitely on external resources
            const setContentTimeout = new Promise<never>((_, reject) =>
                setTimeout(() => reject(new Error('PDF setContent timed out after 30s')), 30_000)
            );
            await Promise.race([
                page.setContent(htmlContent, { waitUntil: 'domcontentloaded' }),
                setContentTimeout
            ]);

            // Generate PDF with separate timeout for large documents
            const pdfRenderTimeout = new Promise<never>((_, reject) =>
                setTimeout(() => reject(new Error('PDF rendering timed out after 60s')), 60_000)
            );
            await Promise.race([
                page.pdf({
                    path: fullPath,
                    format: 'A4',
                    margin: {
                        top: '1cm',
                        right: '1cm',
                        bottom: '1cm',
                        left: '1cm'
                    },
                    printBackground: true
                }),
                pdfRenderTimeout
            ]);

            console.log(`[DocumentGenerator] Generated PDF: ${filename}`);
        } catch (error: any) {
            console.error('[DocumentGenerator] PDF generation failed:', error.message);
            throw new Error(`PDF generation failed: ${error.message}`);
        } finally {
            // Always close browser to prevent leaked Chromium processes
            if (browser) await browser.close().catch(() => {});
        }

        // Get file size
        const stats = fs.statSync(fullPath);

        // Register in database
        await this.registerFile({
            id,
            filename,
            file_type: 'pdf',
            file_path: relativePath,
            title: request.title,
            user_id: userId,
            file_size: stats.size
        });

        return {
            id,
            filename,
            file_type: 'pdf',
            file_path: relativePath,
            full_path: fullPath,
            mime_type: 'application/pdf',
            file_size: stats.size
        };
    }

    /**
     * Build HTML content string (shared between generateHTML and generatePDF)
     */
    private buildHTMLContent(request: HTMLReportRequest): string {
        const style = this.getHTMLStyle(request.style || 'professional');

        let tocHtml = '';
        if (request.includeTableOfContents) {
            tocHtml = '<nav class="toc"><h2>Table of Contents</h2><ul>';
            request.sections.forEach((section, i) => {
                if (section.heading) {
                    tocHtml += `<li><a href="#section-${i}">${section.heading}</a></li>`;
                }
            });
            tocHtml += '</ul></nav>';
        }

        let contentHtml = '';
        request.sections.forEach((section, i) => {
            if (section.heading) {
                const tag = `h${section.level || 2}`;
                contentHtml += `<${tag} id="section-${i}">${section.heading}</${tag}>`;
            }

            if (section.content) {
                contentHtml += `<p>${section.content}</p>`;
            }

            if (section.bullets) {
                contentHtml += '<ul>';
                for (const bullet of section.bullets) {
                    contentHtml += `<li>${bullet}</li>`;
                }
                contentHtml += '</ul>';
            }

            if (section.table) {
                contentHtml += '<table><thead><tr>';
                for (const header of section.table.headers) {
                    contentHtml += `<th>${header}</th>`;
                }
                contentHtml += '</tr></thead><tbody>';
                for (const row of section.table.rows) {
                    contentHtml += '<tr>';
                    for (const cell of row) {
                        contentHtml += `<td>${cell}</td>`;
                    }
                    contentHtml += '</tr>';
                }
                contentHtml += '</tbody></table>';
            }
        });

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${request.title}</title>
    <style>${style}</style>
</head>
<body>
    <header>
        <h1>${request.title}</h1>
        <p class="meta">Generated by AI Co-Worker on ${new Date().toLocaleDateString()}</p>
    </header>
    ${tocHtml}
    <main>
        ${contentHtml}
    </main>
    <footer>
        <p>Generated by AI Partner</p>
    </footer>
</body>
</html>`;
    }

    // Check if libraries are available
    getAvailableGenerators(): { type: string; available: boolean }[] {
        return [
            { type: 'pptx', available: !!this.pptxgenjs },
            { type: 'xlsx', available: !!this.exceljs },
            { type: 'docx', available: !!this.docx },
            { type: 'html', available: true }, // Always available
            { type: 'pdf', available: true } // Requires Playwright
        ];
    }
}

// Singleton instance
export const documentGenerator = new DocumentGenerator();
